language: cpp

sudo: required
 
matrix:
  include:
    # mac
    - os: osx
      osx_image: xcode7.3
      #addons:
      #   brew:
      #      packages:
      env: 
        - BUILD_TARGET=mac 
    # linux
    - os: linux
      addons:
         apt:
            sources:
                - george-edison55-precise-backports #To install cmake 3.2.3 / doxygen 1.8.3
            packages:
               - cmake
               - cmake-data
      env: 
        - BUILD_TARGET=linux 


install:
  # Enable execution of the scripts
  - chmod +x tools/travis-scripts/before-install.sh 
  - chmod +x tools/travis-scripts/run-script.sh
  
  # Run install-environment script
  - tools/travis-scripts/before-install.sh

script:
  # Run test script
  - tools/travis-scripts/run-script.sh

# Caching so the next build will be fast too.
# TODO